name: injectfy
description: A minimalistic and easy-to-use dependency injection library for managing singletons and factories in Dart.
version: 1.0.1
homepage: https://github.com/evandersondev/injectfy
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
